# Generated by Django 5.2.12 on 2026-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExampleModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="A unique key for the example model",
                        max_length=100,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="A value associated with the key",
                        max_length=255,
                        verbose_name="Value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Example Model",
                "verbose_name_plural": "Example Models",
            },
        ),
    ]
